### ISSUE TITLE
0.4.1 deletes any other file in the tree

### ISSUE THREAD

**Issue by cibernox** [rwjblue/broccoli-file-mover#14] opened 2014-10-10 11:42 UTC
I've found a breaking (and probably unintended) behavior in the last version.

While in v 0.3.6 moving some files left the rest of the tree intact, the 0.4.1 deletes all files in the tree but those being moved.

Steps to reproduce:

Working branch: https://github.com/cibernox/ember-cpm/tree/file_mover_issue_old
Failing branch: https://github.com/cibernox/ember-cpm/tree/file_mover_issue

Diff between branches:

``` diff
diff --git a/package.json b/package.json
index caf8953..9ce506c 100644
--- a/package.json
+++ b/package.json
@@ -31,6 +31,6 @@
     "broccoli-uglify-js": "~0.1.3",
     "jshint": "~2.5.0",
     "testem": "~0.6.15",
-    "broccoli-file-mover": "0.3.6"
+    "broccoli-file-mover": "0.4.1"
   }
 }
```

If after running `npm install` yo build the library (just type `make`) you'll see that one build is fine but the other contains only the moved files.

**Comment by rwjblue** [comment] 2014-10-10 11:53
Duplicate of https://github.com/rwjblue/broccoli-file-mover/issues/12.

**Closed as completed by rwjblue** 2014-10-10 11:53 UTC
